In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Gender': ['Male', 'Female', 'Female', 'Male'],
    'City': ['Mumbai', 'Delhi', 'Pune', 'Delhi'],
    'Education': ['Low', 'Medium', 'High', 'Medium']
})



df

,Gender,City,Education
0,Male,Mumbai,Low
1,Female,Delhi,Medium
2,Female,Pune,High
3,Male,Delhi,Medium


In [18]:
# 1. Label Encoding (Alphabetical)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Encoded_Gender'] = le.fit_transform(df['Gender'])
df
# this is done by alphabetical order 
# here F comes first & then M 

,Gender,City,Education,Encoded_Gender
0,Male,Mumbai,Low,1
1,Female,Delhi,Medium,0
2,Female,Pune,High,0
3,Male,Delhi,Medium,1


In [19]:
# 2. Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Low', 'Medium', 'High']]) # this is imp step here (order from low to high)
df['Encoded_Education'] = oe.fit_transform(df[['Education']])
df

,Gender,City,Education,Encoded_Gender,Encoded_Education
0,Male,Mumbai,Low,1,0.0
1,Female,Delhi,Medium,0,1.0
2,Female,Pune,High,0,2.0
3,Male,Delhi,Medium,1,1.0


In [ ]:
# 3. One Hot encoding
# a) method 1
df_encoded = pd.get_dummies(df, columns=['City'])
df_encoded

,Gender,Education,Encoded_Gender,Encoded_Education,City_Delhi,City_Mumbai,City_Pune
0,Male,Low,1,0.0,False,True,False
1,Female,Medium,0,1.0,True,False,False
2,Female,High,0,2.0,False,False,True
3,Male,Medium,1,1.0,True,False,False


In [ ]:
# b) method 2
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False) 
city_encoded = ohe.fit_transform(df[['City']])
print(city_encoded)

# sparse_output = False 
# all values (0 and 1) are stored (matrix)
# sparse_output = True
# only non-zero (1) values are stored (numpy array)


[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [32]:
# 4. Dummy encoding
dummy = pd.get_dummies(df, columns=['City'], drop_first=True)
dummy
# all false means last city

,Gender,Education,Encoded_Gender,Encoded_Education,City_Mumbai,City_Pune
0,Male,Low,1,0.0,True,False
1,Female,Medium,0,1.0,False,False
2,Female,High,0,2.0,False,True
3,Male,Medium,1,1.0,False,False


In [35]:
# 5. Target Encoding
# Replace category with average target value.
data = pd.DataFrame({
    'City': ['Mumbai', 'Delhi', 'Pune', 'Delhi'],
    'Price': [100, 200, 150, 250]
})

city_mean = data.groupby('City')['Price'].mean()
data['City_target_encoded'] = data['City'].map(city_mean)
data

,City,Price,City_target_encoded
0,Mumbai,100,100.0
1,Delhi,200,225.0
2,Pune,150,150.0
3,Delhi,250,225.0
