In [3]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

# 1) reshape into 3x3
# 2) convert it back to 1D using flatten
# 3) transpose the 3x3 matrix
# 4) expand dims of [10,20,30] into (3,1)
# 5) squeeze [[[1,2,3]]] into 1D

[1 2 3 4 5 6 7 8 9]


In [5]:
rr = a.reshape(3,3)
print(rr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(rr.flatten())

[1 2 3 4 5 6 7 8 9]


In [8]:
print(rr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
a2 = np.expand_dims(a, axis=1)
print(a2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [11]:
print(a2.squeeze())

[1 2 3 4 5 6 7 8 9]
