In [2]:
import numpy as np

In [3]:
# 1. random.rand
print(np.random.rand(5))
print()
print(np.random.rand(4, 2))

[0.28415574 0.67058248 0.15992893 0.6170881  0.26747041]

[[0.27823302 0.37864734]
 [0.7415711  0.68249982]
 [0.93789797 0.64523083]
 [0.12232278 0.06334544]]


In [4]:
# 2. random.randn
# It generates random values from (Normal Distribution)
# i.e.  1) mean = 0
#       2) std deviation = 1

print(np.random.randn(5))
print()
print(np.random.randn(4, 2))

[ 0.1127953   1.21733208 -1.27861038 -0.16857766 -1.82269562]

[[ 0.07544284  0.70259384]
 [-1.58452527  0.96834581]
 [ 0.97189998  0.79344657]
 [ 0.5880623   0.27263352]]


In [8]:
# 3. random integer
# np.random.randint(low, high, size)

print(np.random.randint(5, 9, 3))
print()
print(np.random.randint(1, 5, (3, 2)))

[7 5 7]

[[2 3]
 [1 2]
 [2 1]]


In [10]:
# 4. random.choice

print(np.random.choice([55, 98, 34, 21, 60])) # single choice
print() 
print(np.random.choice([55, 98, 34, 21, 60], size = 4)) # with replacement  
print()
print(np.random.choice([55, 98, 34, 21, 60], size = 4, replace = False)) # without replacement  

98

[21 21 60 34]

[60 55 34 21]


In [7]:
# 5. random.seed(any_number)
# always same random output for same number 
# numbers -> gives starting point

np.random.seed(46) 
print(np.random.rand(5))

np.random.seed(91)
print(np.random.rand(5))

np.random.seed(46)
print(np.random.rand(5))

np.random.seed(46)
print(np.random.rand(5))

np.random.seed(91)
print(np.random.rand(5))

[0.78383235 0.63483371 0.24904309 0.75807586 0.31307694]
[0.2010036  0.32902047 0.29649969 0.09333367 0.33307881]
[0.78383235 0.63483371 0.24904309 0.75807586 0.31307694]
[0.78383235 0.63483371 0.24904309 0.75807586 0.31307694]
[0.2010036  0.32902047 0.29649969 0.09333367 0.33307881]
