In [1]:
import numpy as np

In [2]:
# NumPy gives 2 main ways:
# 1. Binary files → fast, best for NumPy arrays
# 2. Text/CSV files → readable, used for sharing

In [7]:
# A) Binary File Handling

# 1. save array
a = np.array([4, 5, 6, 7])
np.save("MyArray.npy", a) # (.npy) file

# 2. load array
b = np.load("MyArray.npy")
print(b)

#  Why Binary is Best?
#  -> very fast
#  -> preserves exact dtype and shape
#  -> smaller file size
#  -> perfect for ML datasets

[4 5 6 7]


In [ ]:
# B) Text/CSV File

# 1. save array (csv / txt)
a = np.array([[1, 2, 3, 4],
              [4, 5, 6, 7]])
np.savetxt("MyArray.csv", a, delimiter=",", fmt="%d") # for csv, delimiterm= "," (fmt="%d" means integer)
np.savetxt("MyArray.txt", a) # for txt , delimiter not required

# 2. load array
b = np.loadtxt("MyArray.csv", delimiter=",") # float by default
c = np.loadtxt("MyArray.csv", delimiter=",", dtype=int) # this gives integer
d = np.loadtxt("MyArray.txt")

print("csv (float by default):")
print(b)
print("\ncsv (int) :")
print(c)
print("\ntxt :")
print(d)

csv (float by default):
[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]

csv (int) :
[[1 2 3 4]
 [4 5 6 7]]

txt :
[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]
