In [1]:
import numpy as np

In [2]:
# 1D array
ar_1 = np.array([3, 5, 7, 4, 0])
print(ar_1)

[3 5 7 4 0]


In [3]:
# 2D array
ar_2 = np.array([
    [2, 4],
    [3, 5],
    [8, 0]
])
print(ar_2)

[[2 4]
 [3 5]
 [8 0]]


In [4]:
ar_3 = np.array([
    [[1, 4], [4, 5]],
    [[6, 7], [9, 0]]
])
print(ar_3)

[[[1 4]
  [4 5]]

 [[6 7]
  [9 0]]]


In [5]:
# 1. no. of dimentions
print(ar_1.ndim)
print(ar_2.ndim)
print(ar_3.ndim)

1
2
3


In [6]:
# 2. shape
print(ar_1.shape)
print(ar_2.shape)
print(ar_3.shape)

(5,)
(3, 2)
(2, 2, 2)


In [7]:
# 3. size (no. of elements)
print(ar_1.size)
print(ar_2.size)
print(ar_3.size)

5
6
8


In [8]:
# 4. datatype
print(ar_2.dtype)

int64


In [9]:
# 5. changing datatype (astype)
float_array = np.array([2, 5.6, 7.5, 8.8])
int_array = float_array.astype(int) # this converts into int
print(float_array)
print(int_array)

[2.  5.6 7.5 8.8]
[2 5 7 8]
