In [2]:
import numpy as np

In [3]:
# 1. zeros
# 1d zeros
ar1 = np.zeros(4)
print(ar1)

[0. 0. 0. 0.]


In [4]:
# 2d zeros
ar2 = np.zeros((3, 2))
print(ar2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
# 2. ones
# 2D ones
ar3 = np.ones((2, 4))
print(ar3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# 3. full
# 2D full with any value
ar4 = np.full((3, 3), 8) # np.full(shape, value)
print(ar4)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [7]:
# 4. arange
# np.arange(start, stop, step)
# 1D array
ar6 = np.arange(3, 13, 2) # stop in not included
print(ar6)

[ 3  5  7  9 11]


In [8]:
# For 2D or 3D array we use .reshape(shape)
print(np.arange(12))
ar7 = np.arange(12).reshape(3, 4) # imp (total elements = rows*cols)
print(ar7)
print(ar7.reshape(3, 2, 2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [9]:
# 5. linspace
# creates evenly spaced numbers between a range
# np.linspace(start, stop, no_of_values)
ar8 = np.linspace(0, 10, 4) # stop is included
print(ar8)

[ 0.          3.33333333  6.66666667 10.        ]


In [10]:
# 6. identity matrix (always 2D)
# np.eye() 
ar9 = np.eye(4)
print(ar9)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# 7. random array creation
# np.random.rand(shape)
# values are in between (0,1)
a = np.random.rand(4)
b = np.random.rand(2, 3)
print("a = ",a)
print("\nb = ",b)

a =  [0.77393028 0.8381479  0.45779146 0.81968616]

b =  [[0.39350668 0.49985555 0.24234633]
 [0.98516423 0.29537059 0.61429248]]


In [12]:
# np.random.randn(shape)
# give random values from "Normal distribution"
a = np.random.randn(2, 3) #2D 
print(a)

[[-0.52792122 -1.05477881  2.28491186]
 [ 1.18413911  1.20843523  0.22379568]]


In [15]:
# np.random.randint(low, high, shape)
a = np.random.randint(3, 10, (2, 3)) #2D random integers (in a range 3 to 10)
print(a)

[[3 7 8]
 [9 4 6]]
