In [2]:
import numpy as np

In [ ]:
# 1. basic indexing (1D)
arr = np.array([30, 50, 20, 60, 70, 10])
# Saurav was here
print(arr[3])
print(arr[1])

60
50


In [13]:
# 2. negative indexing (1D)
print(arr[-1])
print(arr[-3])

10
60


In [5]:
# 3. slicing in 1D
# arr[start: stop: step]
print(arr[1:4])
print(arr[:6]) # from begining
print(arr[4:]) # till end
print(arr[0:5:2]) # every 2nd element 
print(arr[::-1]) # reverse array

[50 20 60]
[30 50 20 60 70 10]
[70 10]
[30 20 70]
[10 70 60 20 50 30]


In [16]:
# 4. indexing in 2D
arr_2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr_2[1, 0])
print(arr_2[2, 1])
print(arr_2[1, -1])

40
80
60


In [7]:
# 5. slicing in 2D
print(arr_2[1]) # whole row
print()
print(arr_2[:, 1]) # whole column
print()
print(arr_2[1:3, 0:2])

[40 50 60]

[20 50 80]

[[40 50]
 [70 80]]


In [8]:
# 6. Fancy indexing
# just add one more bracket
# 1D array:
print("\n(0th, 3rd & 4th index) element : ", arr[[0, 3, 4]]) 


(0th, 3rd & 4th index) element :  [30 60 70]


In [9]:
# 2D array:
print(arr_2[[0, 2]]) #specific rows i.e. r0, r2
print()
print(arr_2[:, [1, 2]]) #specific columns i.e. c1, c2
print()
print(arr_2[[0, 1, 2], [1, 2, 0]]) # this prints elements at indexes (0,1), (1,2), (2,0)

[[10 20 30]
 [70 80 90]]

[[20 30]
 [50 60]
 [80 90]]

[20 60 70]


In [20]:
# 7. Boolean indexing (Filterint)
print(arr[arr > 30])
print()
print(arr[(arr > 10) & (arr < 50)])

[50 60 70]

[30 20]


In [11]:
# boolean array
m = arr < 30
print(m)
print(arr[m])

[False False  True False False  True]
[20 10]


In [12]:
# 2D array 
print(arr_2[(arr_2 < 56) & (arr_2 > 12)])
print()

# 2D Boolean array
m = arr_2 > 20
print(m)

[20 30 40 50]

[[False False  True]
 [ True  True  True]
 [ True  True  True]]
