In [2]:
import numpy as np

In [3]:
# 1. convert 1D to nD
# reshape creates a view
# !! no. of elements should be equal
a1 = np.array([1, 5, 6, 7, 4, 3])
print(a1.reshape(2, 3)) 
print()
print(a1.reshape(3,-1)) # takes shape automatically

[[1 5 6]
 [7 4 3]]

[[1 5]
 [6 7]
 [4 3]]


In [4]:
# 1D to 3D
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a.reshape(2, 2, 2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# 2. nD to 1D
# flatten() & ravel()
a2 = np.array([[1,2,3], [4,5,6]])
f = a2.flatten()
r = a2.ravel()
print("flatten : ", f)
print("ravel : ", r)

flatten :  [1 2 3 4 5 6]
ravel :  [1 2 3 4 5 6]


In [6]:
# changing ravel makes changes in original as it returns view
# changing flatten never affects original
r[0] = 99 #changing 0th index
print("ravel : ", r)
print("original get changes automatically : \n", a2)

ravel :  [99  2  3  4  5  6]
original get changes automatically : 
 [[99  2  3]
 [ 4  5  6]]


In [7]:
# 3.transpose
print(a2.transpose())
#or
print(a2.T)

[[99  4]
 [ 2  5]
 [ 3  6]]
[[99  4]
 [ 2  5]
 [ 3  6]]


In [ ]:
# 4. adding new dimention
# shape changes from (n,) --> (n,1) or (1,n)
a3 = np.array([1, 2, 3, 4, 5])
print(a3.shape)

at_0 = np.expand_dims(a3, axis=0)
# at_0 = np.expand_dims(at_0, axis=2)

print("\nat 0: ")
print("shape : ", at_0.shape) # 1 added at 0 index in shape
print(at_0)

at_1 = np.expand_dims(a3, axis=1)
print("\nat 1: ")
print("shape : ", at_1.shape) # 1 added at 1 index in shape
print(at_1)


(5,)

at 0: 
shape :  (1, 5, 1)
[[[1]
  [2]
  [3]
  [4]
  [5]]]

at 1: 
shape :  (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [11]:
# 5. remove extra dimention
# (n,1,1) or (n,1) or (1,n) ---> (n,)
remove_dim = np.squeeze(at_1) # useless dimentions are removed 
print(remove_dim)
print("shape : ", remove_dim.shape)

[1 2 3 4 5]
shape :  (5,)


In [10]:
# swapping axes
a4 = np.array([[[1,2,3,4], [4,5,6,7]],
               [[4,5,7,6], [6,8,3,2]],
               [[9,8,7,6], [5,4,3,2]]])
print("shape : ", a4.shape)
print(a4)
print("---------------------")
swapped = a4.swapaxes(0, 2) # 0th & 2th dimensions are swapped
print("shape : ", swapped.shape)
print(swapped)

shape :  (3, 2, 4)
[[[1 2 3 4]
  [4 5 6 7]]

 [[4 5 7 6]
  [6 8 3 2]]

 [[9 8 7 6]
  [5 4 3 2]]]
---------------------
shape :  (4, 2, 3)
[[[1 4 9]
  [4 6 5]]

 [[2 5 8]
  [5 8 4]]

 [[3 7 7]
  [6 3 3]]

 [[4 6 6]
  [7 2 2]]]
