In [4]:
import numpy as np

In [5]:
arr = np.array([10, 40, 20, 50])
print(arr + 10)
print(arr - 5)
print(arr * 3)
print(arr ** 2)
print(arr / 10)
print(arr // 6)
print(arr % 4)

[20 50 30 60]
[ 5 35 15 45]
[ 30 120  60 150]
[ 100 1600  400 2500]
[1. 4. 2. 5.]
[1 6 3 8]
[2 0 0 2]


In [6]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a @ b) # dot product : sum of products (10+40+90+160)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
300


In [7]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
print(np.dot(a,b)) # dot product sum of products (10+40+90+160)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
300


In [8]:
c = np.array([4, 16, 9, 64])
print(np.sqrt(c)) # square root
print(np.power(c, 2)) # square
print(np.power(c, 3)) # cube

[2. 4. 3. 8.]
[  16  256   81 4096]
[    64   4096    729 262144]


In [9]:
print(np.exp(a)) # (e^x) exponential
print(np.log(a)) # log(x) logarithm

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]
[2.30258509 2.99573227 3.40119738 3.68887945]


In [10]:
d = np.array([1.2, 2.4, 3.7, 4.8])
print(np.round(d)) # rounding
print(np.floor(d)) # down
print(np.ceil(d))  # up

[1. 2. 4. 5.]
[1. 2. 3. 4.]
[2. 3. 4. 5.]


In [11]:
# Broadcasting
# numpy expands smaller arrays to match bigger array , so operation can happen

a1 = np.array([10, 20])
a2 = np.array([[10, 20], [30, 40]])

print(a1 + 3) # 3 expands to [3, 3]
print()
print(a2 + a1) # here a1 (1D) array expanded to [[10, 20], [10, 20]]
print()

b = np.array([[10],
              [20]])
print(a2 + b) # here b becomes b = [[10, 10], 
                                  # [20, 20]]
 

[13 23]

[[20 40]
 [40 60]]

[[20 30]
 [50 60]]
