In [9]:
import numpy as np

In [10]:
a1 = np.array([6, 4, 9, 3, 1])

a2 = np.array([[3, 7, 1],
               [9, 4, 8]])

In [11]:
print(np.sort(a1))
print()
print(np.sort(a2)) #by default it sort row-wise (axis = -1)
print()
print(np.sort(a2, axis=0)) # column-wise
print()
print(np.argsort(a1)) # sorting by displaying indexes (use it when ranking is needed)

[1 3 4 6 9]

[[1 3 7]
 [4 8 9]]

[[3 4 1]
 [9 7 8]]

[4 3 1 0 2]


In [12]:
# where
# np.where(condition, value_if_true, value_if_false)
print(np.where(a1 > 5))
print()
print(np.where(a1 > 5, 999, a1)) # if true, 999 && if false, as it is (a1)

(array([0, 2]),)

[999   4 999   3   1]


In [15]:
# index of min & max
print("index of min :", np.argmin(a1))
print("index of max :", np.argmax(a1))
print()
print("index of max of 2D:", np.argmax(a2)) #for 2D array it acts as flatten array by default
# we can apply (axis = 0) & (axis = 1) here also for column-wise & row-wise

index of min : 4
index of max : 2

index of max of 2D: 3


In [14]:
x = np.array([40, 20, 40, 30, 20, 40, 60, 70])
print(np.unique(x))

# this is very useful
values, counts = np.unique(x, return_counts = True)
print("Values :", values)
print("Counts :", counts)
print("i.e.  (20 = 2 times), (40 = 3 times) & (others = 1 time)")

[20 30 40 60 70]
Values : [20 30 40 60 70]
Counts : [2 1 3 1 1]
i.e.  (20 = 2 times), (40 = 3 times) & (others = 1 time)
