In [12]:
import numpy as np

In [13]:
# 1. concatenation
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a, b))) #double parethesis is imp (())

[1 2 3 4 5 6]


In [14]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Column-wise: ")
print(np.concatenate((A, B), axis=0))
print("Row-wise: ")
print(np.concatenate((A, B), axis=1))

Column-wise: 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Row-wise: 
[[1 2 5 6]
 [3 4 7 8]]


In [15]:
# 2. stacks
# np.vstack() -- vertical stack
# np.hstack() -- horizontal stack
# np.stack()  -- joins array but create new dimention

print("vstack")
print(np.vstack((A, B)))
print("\nhstack")
print(np.hstack((A, B)))
print("\nstack column wise (adds 3rd dimention):")
print(np.stack((A, B), axis=0))
print("\nstack row wise (adds 3rd dimention):")
print(np.stack((A, B), axis=1))

vstack
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack
[[1 2 5 6]
 [3 4 7 8]]

stack column wise (adds 3rd dimention):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

stack row wise (adds 3rd dimention):
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [18]:
# 3. splitting 
# np.split(array, no_of_parts)
# np.vsplit(array, no_of_parts)
# np.hsplit(array, no_of_parts)

X = np.array([1, 2, 3, 4, 5, 6])
print(np.split(X, 3))


[array([1, 2]), array([3, 4]), array([5, 6])]


In [21]:
Y = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8]])

print(np.hsplit(Y, 4))
print()
print(np.vsplit(Y, 2))

[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
