In [9]:
import numpy as np

In [10]:
# 1. ( dot product = matrix multiplication )
# matrix multiplication
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A@B)
print()
print(np.dot(A, B))

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [11]:
# for 1D 
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b)) # (1*4 + 2*5 + 3*6) = 32
print(a@b)

32
32


In [8]:
# 2. Determinant
print(np.linalg.det(A))

-2.0000000000000004


In [22]:
# 3. Inverse
A_inv = np.linalg.inv(A)
print(A_inv)
print("---------------------------------")
print("\n Matrix multiplication of A and A_inv (Identity matrix) :  [it is aprox]\n")
print(A @ A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]
---------------------------------

 Matrix multiplication of A and A_inv (Identity matrix) :  [it is aprox]

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [26]:
# 4. Eigen values & Eigen vectors
values, vectors = np.linalg.eig(A)
print("Eigen Values : ")
print(values)
print("\nEigen Vectors : ")
print(vectors)

Eigen Values : 
[-0.37228132  5.37228132]

Eigen Vectors : 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [29]:
# 5. solving equations :

#   x + y = 5 
#   x - y = 1

A = np.array([[1, 1],
              [1, -1]])

b = np.array([5, 1])

#  solving for (Ax = b)
x = np.linalg.solve(A, b)
print(x)

[3. 2.]
